### ISSUE TITLE
date is not visible in comments

### ISSUE THREAD

**Issue by adityajayadevan** [liaoyufu-leo/StevensMarketPlace_CS_546_Group16_FinalProject#42]
when we give a comment in item date is not showing only the time is visible
<img width="1169" alt="Screen Shot 2021-12-08 at 12 13 27 AM" src="https://user-images.githubusercontent.com/91096824/145152115-cc0a5255-4990-4d05-a69c-c7a33882ef80.png">

**Comment by liaoyufu-leo** [comment]
fixed
