### ISSUE TITLE
Seller name bug 

### ISSUE THREAD

**Issue by adityajayadevan** [liaoyufu-leo/StevensMarketPlace_CS_546_Group16_FinalProject#43]
when we click seller name inside item it is going to a page which is not created.
<img width="1169" alt="Screen Shot 2021-12-08 at 12 15 06 AM" src="https://user-images.githubusercontent.com/91096824/145152415-ca64131a-8394-477b-9f6a-adaaded188a7.png">
<img width="1169" alt="Screen Shot 2021-12-08 at 12 15 14 AM" src="https://user-images.githubusercontent.com/91096824/145152416-f430d4e2-5929-42d8-a3cf-2434165f86b0.png">

**Comment by liaoyufu-leo** [comment]
fixed
