### ISSUE TITLE
privacy protection

### ISSUE THREAD

**Issue by adityajayadevan** [liaoyufu-leo/StevensMarketPlace_CS_546_Group16_FinalProject#44]
I think we should hide the card details

<img width="1169" alt="Screen Shot 2021-12-08 at 12 24 09 AM" src="https://user-images.githubusercontent.com/91096824/145153175-0eca401f-b43c-4eb4-bf58-810a2e53aef9.png">

**Comment by liaoyufu-leo** [comment]
fixed
